### ISSUE TITLE
evaluate use of gsutil -m -o   on delete

### ISSUE THREAD

**Issue by steveobd** [chees/datastore2bigquery#1]
I receive this warning.  Of course, the script can be easily modified, but haven't had time to actually look into it.

==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m -o ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.

**Comment by chees** [comment]
Fixed: https://github.com/chees/datastore2bigquery/commit/4851a0889057e87b16627da8546960f0f02e9ac3
